#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

ls -la $install_dir

ynh_go_install 

ls -la $install_dir

pushd $install_dir/build/
    # Tweak upstream code to add support for subpath install via creation of PASSED_SUBPATH env variable (defaulting to "/")
    sed -i '/^import (/a \\t"fmt"' main.go #add fmt module import
    sed -i '/^\tvar address string/i \\tvar subpath string' main.go 
    sed -i '/env("PASSED_ADDRESS", &address, ":3000")/i \\tenv("PASSED_SUBPATH", &subpath, "/")' main.go 
    sed -i '/handler := http\.Handler(mux)/a \\tstr_get_root := fmt.Sprintf("GET %d", subpath)' main.go
    sed -i '/str_get_root :=/a \\tstr_post_api_pw := fmt.Sprintf("POST %dapi/password", subpath)' main.go
    sed -i '/str_post_api_pw :=/a \\tstr_get_api_pw_id := fmt.Sprintf("GET %dapi/password/{id}", subpath)' main.go
    sed -i '/str_get_api_pw_id :=/a \\tstr_head_api_pw_id := fmt.Sprintf("HEAD %dapi/password/{id}", subpath)' main.go
    sed -i 's/"GET \/"/str_get_root/g' main.go
    sed -i 's/"POST \/api\/password"/str_post_api_pw/g' main.go 
    sed -i 's/"GET \/api\/password\/{id}"/str_get_api_pw_id/g' main.go 
    sed -i 's/"HEAD \/api\/password\/{id}"/str_head_api_pw_id/g' main.go
    sed -i '/^\tlog.Printf("Listening on/a \\tlog.Printf("URL path: \"%s\"", subpath)' main.go 

    # Build
	ynh_hide_warnings ynh_exec_as_app go build -o $install_dir/
popd

ls -la $install_dir

ynh_go_remove
ynh_safe_rm "$install_dir/build/"

chmod +x "$install_dir/passed"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add_systemd
yunohost service add "$app" --description="PassED, share a password securely" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

### `ynh_systemctl` is used to start a systemd service for an app.
### Only needed if you have configure a systemd service
### If you're not using these lines:
###   - Remove the section "STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the backup script
###   - As well as the section "START SYSTEMD SERVICE" in the restore script
###   - As well as the section"STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the upgrade script
###   - And the section "STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the change_url script

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
