#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

ynh_go_install 

pushd $install_dir/build/
    # Tweak upstream code to add support for subpath install via creation of PASSED_SUBPATH env variable (defaulting to "/")
    sed -i '/^import (/a \\t"fmt"' main.go #add fmt module import
    sed -i '/^\tvar address string/i \\tvar subpath string' main.go
    sed -i '/^\tvar subpath string/i \\tvar trimmedSubpath string' main.go
    sed -i '/env("PASSED_ADDRESS", &address, ":3000")/i \\tenv("PASSED_SUBPATH", &subpath, "/")' main.go 
    sed -i '/handler := http\.Handler(mux)/a \\tstrGetRoot := fmt.Sprintf("GET %d", subpath)' main.go
    sed -i '/strGetRoot :=/a \\tstrPostApiPw := fmt.Sprintf("POST %d/api/password", trimmedSubpath)' main.go
    sed -i '/strPostApiPw :=/a \\tstrGetApiPwId := fmt.Sprintf("GET %d/api/password/{id}", trimmedSubpath)' main.go
    sed -i '/strGetApiPwId :=/a \\tstrHeadApiPwId := fmt.Sprintf("HEAD %d/api/password/{id}", trimmedSubpath)' main.go
    sed -i 's/"GET \/"/strGetRoot/g' main.go
    sed -i 's/"POST \/api\/password"/strPostApiPw/g' main.go 
    sed -i 's/"GET \/api\/password\/{id}"/strGetApiPwId/g' main.go 
    sed -i 's/"HEAD \/api\/password\/{id}"/strHeadApiPwId/g' main.go
    sed -i '/handler := http\.Handler(mux)/a \\tif subpath == "\/" {' main.go
    sed -i '/^\tif subpath == "\/"/a \\t\ttrimmedSubpath = ""' main.go
    sed -i '/trimmedSubpath = ""/a \\t\ttrimmedSubpath = subpath' main.go
    sed -i '/trimmedSubpath = ""/a \\t} else {' main.go
    sed -i '/^\t\ttrimmedSubpath = subpath/a \\t}' main.go
    sed -i '/^\tlog.Printf("Listening on/a \\tlog.Printf("URL path: %s", subpath)' main.go
    sed -i '/FileServerFS/a \\tmux.Handle(subpath+"/", http.StripPrefix(subpath, fs))' main.go 
    sed -i '/FileServerFS/a \\tfs := http.FileServer(http.FS(staticFS))' main.go
    sed -i '/FIleServerFS/d' main.go
    sed -i "s|=\"/\([^>]\)|=\"${path%/}/\1|g" static/index.html
    sed -i "s|\(const res = await fetch(.\)/|\1${path%/}/|g" static/js/lang.js
    sed -i "s|\(const res = await fetch(.\)/|\1${path%/}/|g" static/js/api.js

    cat main.go

    # Build
	ynh_hide_warnings ynh_exec_as_app go build -o $install_dir/
popd

ynh_go_remove
ynh_safe_rm "$install_dir/build/"
ynh_safe_rm "$install_dir/.cache/"
ynh_safe_rm "$install_dir/.config/"

chmod +x "$install_dir/passed"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add_systemd
yunohost service add "$app" --description="PassED, share a password securely" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
